import Head from "next/head";
import nookies from "nookies";
import { getCitiesFromToken, getEmailFromToken } from "@/functions/auth";
import Image from "next/image";
import { Inter } from "next/font/google";
import NoUserCities from "@/components/noUserCities";
import UserCities from "@/components/userCities";
import { getRandomCitiesData } from "@/functions/randomCitiesData";
import { cityForFE, openWeatherData } from "@/interfaces/fetchedData";
import bg1 from "../../public/bg1.jpg";
import CitySearch from "@/components/citySearch";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data, user }: { data: any; user: string }) {
  console.log(data[0]);

  return (
    <>
      <Head>
        <title>Weather-App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="fixed w-screen h-screen -z-10">
        <Image
          src={bg1}
          alt="Picture of the author"
          width={1920}
          height={1280}
          className="w-full h-full object-cover"
        />
      </div>

      <h1 className="text-center text-yellow-200 w-screen text-[100px]">
        Weather in the world
      </h1>
      <main className="w-screen">
        <CitySearch />
      
        {user ? <UserCities user={user} /> : <NoUserCities data={data} />}
      </main>
    </>
  );
}

export async function getServerSideProps(ctx: any) {
  // Parse
  const cookies = nookies.get(ctx);
  let cities: cityForFE[] | null;
  let countries: string[] = [];
  let user: string | null;
  let data: openWeatherData[] = [];
  try {
    //cities = getCitiesFromToken(cookies.accessToken);
    user = getEmailFromToken(cookies.accessToken);
  } catch (error) {
    cities = null;
    user = null;
  }
  if (user) {
  } else {
    cities = await getRandomCitiesData(12);
    for (let i = 0; i < cities.length; i++) {
      data.push(
        await (
          await fetch(
            `https://api.openweathermap.org/data/2.5/weather?q=${cities[i].city}&units=metric&APPID=84fe0ab7b8e1da2d85374181442b3639`
          )
        ).json()
      );
      data[i].sys = { ...data[i].sys, countryLong: cities[i].country_long };
    }
  }

  return {
    props: { user, data }, // will be passed to the page component as props
  };
}
