import Head from "next/head";
import { parseCookies, setCookie, destroyCookie } from "nookies";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Logout() {
  const cookies = parseCookies();
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Weather - App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
        <button
          onClick={() => {
            destroyCookie(null, "accessToken");
            router.push("/")
          }}
        >Logout</button>
      </main>
    </>
  );
}
